### PR TITLE
created ipynb for age difference data cleaning, cleaned data in age-d…

### PR DESCRIPTION
**Pull request by rguo99**

### CODE REVIEW

**Review by jebking — CHANGES_REQUESTED** [review]
I think you should change the title and documentation at the top of the python notebook to make it clear that it processes data for the age difference vis and not for the matrix vis

**Comment by rguo99** [comment]
Documentation confusion resolved! Also, I've made new commits in which I updated the ipynb so the age-vis dataset would have the marital status variable as well. Can I merge the two now? 

On a side note, once I merge the age_vis branch with master, in the future, do I continue making commits to the age_vis branch, and then pull request to merge the two branch each time I make a commit? Or is this pull request thing a one time thing?

**Comment by jebking** [comment]
You can continue to work on this branch, since it's dedicated to the age vis feature. Typically, I'll start a completely new branch for every pull request.

You just need to make sure to merge master back into the branch whenever it updates.

**Review by jebking — APPROVED** [review]
Looks great :)

**Pull request merged**
